# Используем официальный Python-образ
FROM python:3.9

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта
COPY . .

# Устанавливаем зависимости
RUN pip install fastapi uvicorn pydantic

# Создаём том для хранения данных
VOLUME /app/data

# Устанавливаем переменную окружения для базы данных
ENV DATABASE_PATH=/app/data/shorturl.db

# Команда запуска приложения
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
